### PR TITLE
Add an extention option to surport scss/less files

### PR DESCRIPTION
**Pull request by hzsrc**
Current versions dosn't surport scss files, only scan css files under styleLibraryName folder.
I tried to add an extention option in core.js and it can works. With this I don't need to transform scss to css first, just use the scss files directly.

### CODE REVIEW

**Comment by hzsrc** [comment]
Use like this:
[
      "component",
      [
        {
          "libraryName": "element-ui",
          "styleLibraryName": "~node_modules/element-theme-chalk/src",
          **"ext": "scss"**
        }
      ]
    ]


[core.zip](https://github.com/ant-design/babel-plugin-import/files/1599203/core.zip)

**Comment by hzsrc** [comment]
只是添加了一个 "ext" 的配置项，用于支持scss源码的按需加载。

**Comment by sorrycc** [comment]
重新提个 PR 吧，diff 没法看啊。

**Comment by hzsrc** [comment]
[core.zip](https://github.com/ant-design/babel-plugin-import/files/1599683/core.zip)
这个是1.0.0上改的core.js，看下可以吗？

**Pull request closed without merging**
